# EGRMGMT 590.10 Homework 1

*Due at 6:15pm ET on Thursday, January 24*

## Instructions

+ Make sure you have pandas, NumPy, and pydataset installed before working on the assignment.
+ There are 20 questions in total. The first 15 questions requires coding and the last 5 does not.
    + For the 15 coding questions, submit both your code and the results upon running your code.
    + For the 5 non-coding questions, submit your answers using Markdown or comments.
+ Each question is worth 0.5 points. Your grades are based on the accuracy of the results, not the code execution speed.
+ You can work on questions in your preferred order as the questions are independent with each another.
+ Submit the .ipynb file to Sakai before 6:15pm ET on Thursday, January 24.
+ Assignments handed in late will lose 1 point every 24-hour window after 6:15pm ET on Thursday, January 24.

## Coding Questions

### Question 1

Use an IPython built-in magic command to return the current working directory path

In [1]:
%pwd

'C:\\Users\\maddh'

### Question 2

Create a for loop to update the dictionary by_length which groups the words in the list word_samples by the length of words. The keys in by_length are the lengths of words.

In [8]:
word_samples = ['chalk', 'awk', 'pear', 'algebra', 'tie', 'nut', 'physics', 'magnolia', 'sycamore']
by_length = {} 

In [10]:
for word in word_samples: 
    by_length.update({len(word):word}) #Updating the dictionary with words(as values) and their length(as keys)
by_length

{5: 'chalk', 3: 'nut', 4: 'pear', 7: 'physics', 8: 'sycamore'}

### Question 3

Use the map and lambda functions to create a list numbers_sq which contains the squared value of each element in the list numbers 

In [11]:
numbers = [1, 2, 3, 4]

In [13]:
numbers_sq = map(lambda x : x*x, numbers)    #returns a list after applying lambda function for squaring elements in list 
print(list(numbers_sq))

[1, 4, 9, 16]


### Question 4

Select every other element from list1 starting from the element with index = 1.

In [14]:
import numpy as np
np.random.seed(42)
list1 = np.random.randint(0,10,20)
list1

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4, 1, 7, 5, 1])

In [15]:
list1[1: :2]  #selecting and slicing the list with the given step

array([3, 4, 9, 6, 4, 7, 2, 4, 7, 1])

### Question 5

Rename the columns 0, 1, and 2 in the Dataframe df0 to "apple", "banana", and "orange" respectively

In [16]:
import pandas as pd, numpy as np
np.random.seed(42)
df0 = pd.DataFrame(np.random.randint(low=0, high=5, size=(5, 3)))
df0

0  1  2
0  3  4  2
1  4  4  1
2  2  2  2
3  4  3  2
4  4  1  3

In [27]:
df0.rename(columns={0:'apple',1:'banana',2:'orange'},inplace=True)  
df0

apple  banana  orange
0      3       4       2
1      4       4       1
2      2       2       2
3      4       3       2
4      4       1       3

### Question 6

Identify names of columns in the Dataframe df1 which have missing values

In [28]:
import pandas as pd, numpy as np
sample_data = {'a': [5, 8, 2, 0], 'b': [7, 9, np.NaN, 1], 'c': [np.NaN, 3, 2, 8] }
df1 = pd.DataFrame(data = sample_data)
df1

a    b    c
0  5  7.0  NaN
1  8  9.0  3.0
2  2  NaN  2.0
3  0  1.0  8.0

In [150]:
df1.isnull().any() #returns true against the name of columns satisfying the condition

a    False
b     True
c     True
dtype: bool

### Question 7

Select rows in the Dataframe df1 which have no missing values in both column b and c

In [43]:
import pandas as pd, numpy as np
sample_data = {'a': [5, 8, 2, 0], 'b': [7, 9, np.NaN, 1], 'c': [np.NaN, 3, 2, 8] }
df1 = pd.DataFrame(data = sample_data)
df1

a    b    c
0  5  7.0  NaN
1  8  9.0  3.0
2  2  NaN  2.0
3  0  1.0  8.0

In [74]:
rows = df1[df1.isnull().any(1) == False] #select rows satisfying the condition 
rows

a    b    c
1  8  9.0  3.0
3  0  1.0  8.0

### Question 8

Use the Dataframe df2 and calculate the average Sepal.Length and Sepal.Width of all the instances whose Species are versicolor or virginica

In [82]:
!pip install pydataset

  Running setup.py bdist_wheel for pydataset: started
  Running setup.py bdist_wheel for pydataset: finished with status 'done'
  Stored in directory: C:\Users\maddh\AppData\Local\pip\Cache\wheels\fe\3f\dc\5d02ccc767317191b12d042dd920fcf3432fab74bc7978598b
Successfully built pydataset


In [20]:
from pydataset import data
import pandas as pd
df2 = data('iris')
df2.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [22]:
df2new = df2.loc[df2.Species != 'setosa']  #creating new dataframe satifying the condition
sepal_len_avg = df2new['Sepal.Length'].sum()/df2new['Sepal.Length'].count() 
sepal_width_avg = df2new['Sepal.Width'].sum()/df2new['Sepal.Width'].count()
print("Average sepal length is:", sepal_len_avg)
print( "Average sepal width is:", sepal_width_avg)

Average sepal length is: 6.2620000000000005
Average sepal width is: 2.8719999999999994


### Question 9

For the Dataframe df3, return the names of columns whose data type is 'int64'

In [119]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...    Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...       power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...       power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...       power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...       power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...       power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [146]:
print(df3.loc[:, df3.dtypes == np.int64].any().index.values)  #returns index values for the given condition

['Length' 'Luggage' 'Wheel.base' 'Width']


### Question 10

1) Add a new column 'Size' to the Dataframe df3 which sums up the Height, Length, and Width for each row

2) Calculate the summary statistics of the column 'Size', e.g. count, mean, standard deviation, minimum, 1st quartile, median, 3rd quartile, and maximum

In [151]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...    Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...       power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...       power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...       power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...       power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...       power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [158]:
df3['Size']=df3.Height+df3.Length+df3.Width #creating a new column
df3['Size'].describe() 

count    111.000000
mean     299.635135
std       18.774977
min      256.000000
25%      286.750000
50%      299.000000
75%      311.750000
max      351.000000
Name: Size, dtype: float64

### Question 11

Identify the row index label (i.e. the car model) for the car with the most weight in the Dataframe df3 

In [159]:
from pydataset import data
import pandas as pd
df3 = data('car90')
df3.head()

Country   Disp  Disp2  Eng.Rev  Front.Hd  Frt.Leg.Room  \
Acura Integra    Japan  112.0    1.8   2935.0       3.5          41.5   
Acura Legend     Japan  163.0    2.7   2505.0       2.0          41.5   
Audi 100       Germany  141.0    2.3   2775.0       2.5          41.5   
Audi 80        Germany  121.0    2.0   2835.0       4.0          42.0   
BMW 325i       Germany  152.0    2.5   2625.0       2.0          42.0   

               Frt.Shld  Gear.Ratio  Gear2     HP  ...    Steering  Tank  \
Acura Integra      53.0        3.26   3.21  130.0  ...       power  13.2   
Acura Legend       55.5        2.95   3.02  160.0  ...       power  18.0   
Audi 100           56.5        3.27   3.25  130.0  ...       power  21.1   
Audi 80            52.5        3.25   3.25  108.0  ...       power  15.9   
BMW 325i           52.0        3.02   2.99  168.0  ...       power  16.4   

                Tires  Trans1  Trans2 Turning     Type  Weight  Wheel.base  \
Acura Integra  195/60   man.5  auto.4    37.0    Small  2700.0         102   
Acura Legend   205/60   man.5  auto.4    42.0   Medium  3265.0         109   
Audi 100       205/60   man.5  auto.3    39.0   Medium  2935.0         106   
Audi 80        175/70   man.5  auto.3    35.0  Compact  2670.0         100   
BMW 325i       195/65   man.5  auto.4    35.0  Compact  2895.0         101   

               Width  
Acura Integra     67  
Acura Legend      69  
Audi 100          71  
Audi 80           67  
BMW 325i          65  

[5 rows x 34 columns]

In [185]:
df3['Weight'].idxmax() #returns the index associated with the maximum value of the specified column

'Cadillac Brougham'

### Question 12

Create a dictionary dict1 in which each key is an even number in list2 and each value is half of the corresponding key

In [186]:
import numpy as np
np.random.seed(42)
list2 = np.random.randint(0,100,20)
list2

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37])

In [193]:
dict1 = {}
for num in list2:
    if(num%2==0):
        dict1.update({num:num/2})
dict1

{92: 46.0,
 14: 7.0,
 60: 30.0,
 20: 10.0,
 82: 41.0,
 86: 43.0,
 74: 37.0,
 2: 1.0,
 52: 26.0}

### Question 13

Replace the missing values in the Dataframe df4 with the average value in each corresponding column

In [24]:
import pandas as pd, numpy as np
sample_data = {'Category': ['A', 'B', 'C', 'D'] * 2
               , 'Value1': [np.nan, 78, 82, 72, np.nan, 90, np.nan, 87]
               , 'Value2': [84, np.nan, 81, 74, 68, np.nan, np.nan, 91]
               , 'Value3': [83, 69, 73, 77, np.nan, 90, 89, 74]
              }
df4 = pd.DataFrame(data = sample_data)
df4

Category  Value1  Value2  Value3
0        A     NaN    84.0    83.0
1        B    78.0     NaN    69.0
2        C    82.0    81.0    73.0
3        D    72.0    74.0    77.0
4        A     NaN    68.0     NaN
5        B    90.0     NaN    90.0
6        C     NaN     NaN    89.0
7        D    87.0    91.0    74.0

In [25]:
df4.fillna(df4.mean())  #filling NaN positions  

Category  Value1  Value2     Value3
0        A    81.8    84.0  83.000000
1        B    78.0    79.6  69.000000
2        C    82.0    81.0  73.000000
3        D    72.0    74.0  77.000000
4        A    81.8    68.0  79.285714
5        B    90.0    79.6  90.000000
6        C    81.8    79.6  89.000000
7        D    87.0    91.0  74.000000

### Question 14

Write a function named isPhoneNumber() to check whether a given string is a phone number with the same pattern as '919-684-2200'. Return True if the patterns match. Otherwise, return False.

In [2]:
import re
def isPhoneNumber(num): 
    """Tells whether the entered string is in the following format or not: '919-684-2200'"""
    num=num.replace(" ","") #removing any space in the input string
    match_num=re.search(r'^(\d{3})-(\d{3})\-(\d{4})$', num) #matching string using regex
    return(bool(match_num))

In [3]:
isPhoneNumber(' 921  - 898 - 7777')

True

In [6]:
isPhoneNumber("923-897-2222")

True

### Question 15

The copy() method is often used to create a copy of a list so that changing the values in the copy doesn't change the values in the original list (see the example as below).

In [232]:
import numpy as np
import copy
arr = np.arange(5)
arr_copy = copy.copy(arr)
arr_copy[0] = 100
print(arr)
print(arr_copy)

[0 1 2 3 4]
[100   1   2   3   4]


However, when the original list is a nested list, the copy() method doesn't function as expected, i.e. changing the values in the copy may change the values in the original list as well (see the example as below).

In [233]:
arr = [[100,200,300], 1, 2, 3, 4]
arr_copy = copy.copy(arr)
arr_copy[0][0] = 111
print(arr)
print(arr_copy)

[[111, 200, 300], 1, 2, 3, 4]
[[111, 200, 300], 1, 2, 3, 4]


Finish the following code and create a more *advanced* copy of the original list, so that the values in the original list won't change when we change the values in the copy.

In [235]:
arr = [[100,200,300], 1, 2, 3, 4]
arr_copy = copy.deepcopy(arr) #deepcopy allows the values in the original list to not change as we change the copy
arr_copy[0][0] = 111
print(arr)
print(arr_copy)

[[100, 200, 300], 1, 2, 3, 4]
[[111, 200, 300], 1, 2, 3, 4]


## Non-Coding Questions

### Question 16

What's the main difference between the "==" and "is" operations?

#### '==' and 'is' are both Comparision operators. 
#### 'is' operator compares the identity of two objects, i.e. are they pointing to the same object or not.
#### '==' operator compares the values of two objects, i.e. the value store in those objects are equal or not.

### Question 17

What's the main difference between the append() and insert() list methods?

#### "append(entry)" adds new entry at the end of list while "insert(position, entry)" adds new entry at the specified position in the list.

In [17]:
list1 = [1,2]

In [18]:
list1.append(3)
print(list1)

[1, 2, 3]


In [19]:
list1.insert(1,3)
print(list1)

[1, 3, 2, 3]


### Question 18

What's the main difference between the pass and continue statements?

#### Continue statement is generally used in a loop, it gives back the control to the start of the loop for the next iteration 
#### Pass statement is a null operation, its function is to do nothing. Its generally used when you need a code syntactically but don't have anything as of now.

### Question 19

What's the main difference between a list and a dictionary?

### List:
####         *Datastructure of python,
####         *heterogenious container of items, 
####         *elements need not be unique,
####         *Mutable, i.e. you can make changes with the existing elements of the list,
####         *Ordered, i.e. the way you enter/update a list, it gets printed in the same order.


### Dictionary:
####         *Datastructure of python,
####         *stored as key:value pair, 
####         *keys have to be unique, elements/values corresponding to the keys need not be unique,
####         *Mutable, i.e. you can make changes with the existing elements of the list,
####         *Not Ordered, i.e. the way you enter/update a list, it is not printed in the same order.

### Question 20

What's the return value of a call to a function which doesn't have a return statement?

#### None